### ISSUE TITLE
FreeCad 0.18.4 Addons are missing.

### ISSUE THREAD

**Issue by laguilar506** [FreeCAD/FreeCAD-addons#178] opened 2020-10-17 00:46 UTC
Greetings from Costa Rica. I just downloaded version 0.18.4 and there is just one addon showing (3D_Pinting_tools), Have tried to install the repository however, they do not show in Tools/Addons Manager. Any suggestions on how this issue can be fix. Thank you.

**Comment by luzpaz** [comment] 2020-10-17 10:00
Dupe of #176

**Closed by luzpaz** 2020-10-17 10:00 UTC
